on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'printing folder contents part2'
        run: ls
      
      - uses: actions/checkout@v3
      
      -name: "login to docker hup"
       run: docker login --username yousefahmed009 --password dckr_pat_eijHB8_ysB9EnKFFj_PWUNwxL70
     
        






