on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'berore'
        run: ls
      
      - uses: actions/checkout@v3
      
      - name: 'after'
        run: ls
     
        






